### ISSUE TITLE
Last character of timer variable name is ignored.

### ISSUE THREAD

**Issue by koutsnGR** [flowsforapex/apex-flowsforapex#200]
**FlowforApex: FlowsforAPEX_v5.1.0**

When setting a timer variable we define a Timer Definition like this &F4A$<variable>. 
e.g: &F4A$myDuration

The variable is in package **FLOW_TIMERS_PKG** evaluated.
The evalution happens like this **substr(l_timer_def,6,length(l_timer_def)-6)**.
l_timer_def :=
            flow_process_vars.get_var_vc2
            ( 
              pi_prcs_id  => pi_prcs_id
            , pi_var_name => **substr(l_timer_def,6,length(l_timer_def)-6)**
            )
          ;
This way, the last character of the variable name is ignored. 

We had to set the variable like this , in order for our example to work.
flow_process_vars.set_var ( pi_prcs_id   => flow_plsql_runner_pkg.get_current_prcs_id
                              , pi_var_name  => 'myDuratio'
                              , pi_vc2_value => 'PT10S'
                              );
If we define the pi_var_name  as 'myDuration', then the variable name is not found.

A substring that pickts the whole variable name , could look like this:
l_timer_def :=
            flow_process_vars.get_var_vc2
            ( 
              pi_prcs_id  => pi_prcs_id
            , pi_var_name => **substr(l_timer_def,6,length(l_timer_def)-6+1)**
            )
          ;

**Comment by commi235** [comment]
Implementation will be replaced by general function based on existing flow_process_vars package.
Exposing respective utility methods to grep and prepare variable names.

**Comment by commi235** [comment]
Just noticed something on this one.
We expect variables to be included like this `&F4A$myDuration.` (mind the `.` at the end)
This is in line with so called exact substitutions which are now standard.
This was the reason for cutting out the last character in above code.

I would propose you adapt your definition accordingly as the same will be required with the revised variable substitution system.

**Comment by koutsnGR** [comment]
Thank you for the solution. I will change my variable definition accordinly.

**Comment by commi235** [comment]
Ticket will be utilised to modernise variable substitution system.
Therefore reopening and moving out of 5.1.2 milestone.
