### ISSUE TITLE
Extend User Task to a) call external URLs and b) make use of APEX metadata.

### ISSUE THREAD

**Issue by nielsdebr** [flowsforapex/apex-flowsforapex#284]
a) Sometimes you would like to call a non-APEX form for a user task that shows up in the inbox view.

b) By specifying the APEX app and the APEX page, you could display a LOV that leverages APEX metadata instead of a text field.

**Comment by rallen2010** [comment]
Call URL put into separate enhancement request for future release.  Using APEX metadata for APEX Page call on userTask released in 22.1
