### ISSUE TITLE
For a happy developer set the application icon

### ISSUE THREAD

**Issue by madmexx2002** [flowsforapex/apex-flowsforapex#335]
For a happy developer set the application icon in the application builder for Flows for Apex.
Icon is already there just reference it under:
Application Definition Attributes / Application Icon => Icon File Name: app-100-logo.png

**Comment by LouisMoreaux** [comment]
Really good idea, thanks. Just test it and it looks good in dark mode builder but not in light mode.
I think we have to generate a new icon specifically for the builder.

**Comment by madmexx2002** [comment]
Just created a new one. Set the background color to the themes blue: f4a_app_builder.png is the icons. The others are the preview for light and dark mode.

![Dark Mode](https://user-images.githubusercontent.com/36326420/135079647-639a0965-bf1d-45db-bdb1-6c36daae9e08.PNG)
![Light Mode](https://user-images.githubusercontent.com/36326420/135079653-b3f08716-7fa3-4c5f-92af-8ed14082b7dd.PNG)
![f4a_app_builder](https://user-images.githubusercontent.com/36326420/135079649-5db3e24e-dd7b-45f1-a838-479c4efc11dd.png)
