### ISSUE TITLE
Optimize code input on modeler's properties panel

### ISSUE THREAD

**Issue by damthor** [flowsforapex/apex-flowsforapex#339]
Entering sql or pl/sql code in the input fields on the properties panel is not very user friendly as they are default text fields. Possible solutions to improve that:

- choose monospace font (possible via css)
- add syntax highlighting (needs further research on existing approaches from bpmn.io, apex or external libraries (e.g. prismjs))

**Comment by nielsdebr** [comment]
Or use the monaco editor as in APEX? :)

**Comment by rallen2010** [comment]
If we could, it would also be nice to add a code 'Validate' button to the editor, as in the APEX code editor, which checked code by parsing it.
