### ISSUE TITLE
Oracle apex 21.2 support 

### ISSUE THREAD

**Issue by j209** [flowsforapex/apex-flowsforapex#379]
Hi
1-What about apex 21.2 support?
2-Since oracle DB 21c [adds the ability to execute JavaScript code directly in the database](https://medium.com/graalvm/mle-executing-javascript-in-oracle-database-c545feb1a010)
What will be the impact on this project?

**Comment by nielsdebr** [comment]
Thanks for your questions. We support* APEX 21.2 as well as upcoming APEX releases. Did you find anything not working?

There are currently no plans for executing JavaScript in the database as we try to support DB 12.2 (and higher) as long as possible.

*) Bear in mind that this is an open source community project where people invest a lot of their spare time.

**Comment by rallen2010** [comment]
What were you hoping for us to support that we don't already do for D 21C or Apex 21.2?

**Comment by rallen2010** [comment]
Closing this as no details provided.
