### ISSUE TITLE
[bug]: Error in process viewer plugin 

### ISSUE THREAD

**Issue by Asterix7m** [flowsforapex/apex-flowsforapex#390]
### Flows for APEX version

21.1

### Oracle Database version

19

### Oracle APEX version

20.1

### What happened?

I see a bug using the viewer plugin.

The Apex debug report is below.

I think the problem is that the table alias ("x") is not used in the _where_ clause.

i.e. 
_select x.* from "FLOWS"."FLOW_INSTANCE_DETAILS_VW" x 
where(FLOW_INSTANCE_DETAILS_VW.PRCS_ID = :PROCESS_ID_

fails, but

_select x.* from "FLOWS"."FLOW_INSTANCE_DETAILS_VW" x 
where(x.PRCS_ID = :PROCESS_ID_
 works

Apex Debug:

- ora_sqlerrm: ORA-00904: "FLOW_INSTANCE_DETAILS_VW"."PRCS_ID": invalid identifier
ORA-06512: at "APEX_200100.WWV_FLOW_DYNAMIC_EXEC", line 1539
ORA-06512: at "APEX_200100.WWV_FLOW_DYNAMIC_EXEC", line 2658
ORA-06512: at "APEX_200100.WWV_FLOW_EXEC", line 2684
ORA-06512: at "APEX_200100.WWV_FLOW_DYNAMIC_EXEC", line 886
ORA-06512: at "SYS.WWV_DBMS_SQL_APEX_200100", line 581
ORA-06512: at "SYS.DBMS_SYS_SQL", line 1658
ORA-06512: at "SYS.WWV_DBMS_SQL_APEX_200100", line 567
ORA-06512: at "APEX_200100.WWV_FLOW_DYNAMIC_EXEC", line 2127
ORA-06512: at "APEX_200100.WWV_FLOW_DYNAMIC_EXEC", line 2101
ORA-06512: at "APEX_200100.WWV_FLOW_DYNAMIC_EXEC", line 865
ORA-06512: at "APEX_200100.WWV_FLOW_DYNAMIC_EXEC", line 908
ORA-06512: at "APEX_200100.WWV_FLOW_EXEC_LOCAL", line 212
ORA-06512: at "APEX_200100.WWV_FLOW_EXEC_LOCAL", line 1345
ORA-06512: at "APEX_200100.WWV_FLOW_EXEC", line 2675
ORA-06512: at "APEX_200100.WWV_FLOW_EXEC", line 2356
ORA-06512: at "APEX_200100.WWV_FLOW_EXEC_API", line 1080
ORA-06512: at "FLOWS~

	4	
0%
0.01429	0.00001	

- error_backtrace: ORA-06512: at "SYS.DBMS_SYS_SQL", line 1658
ORA-06512: at "SYS.WWV_DBMS_SQL_APEX_200100", line 567
ORA-06512: at "APEX_200100.WWV_FLOW_DYNAMIC_EXEC", line 1539
ORA-06512: at "APEX_200100.WWV_FLOW_DYNAMIC_EXEC", line 2658
ORA-06512: at "APEX_200100.WWV_FLOW_EXEC", line 2684
ORA-06512: at "APEX_200100.WWV_FLOW_DYNAMIC_EXEC", line 886
ORA-06512: at "SYS.WWV_DBMS_SQL_APEX_200100", line 581
ORA-06512: at "SYS.DBMS_SYS_SQL", line 1658
ORA-06512: at "SYS.WWV_DBMS_SQL_APEX_200100", line 567
ORA-06512: at "APEX_200100.WWV_FLOW_DYNAMIC_EXEC", line 2127
ORA-06512: at "APEX_200100.WWV_FLOW_DYNAMIC_EXEC", line 2101
ORA-06512: at "APEX_200100.WWV_FLOW_DYNAMIC_EXEC", line 865
ORA-06512: at "APEX_200100.WWV_FLOW_DYNAMIC_EXEC", line 908
ORA-06512: at "APEX_200100.WWV_FLOW_EXEC_LOCAL", line 212
ORA-06512: at "APEX_200100.WWV_FLOW_EXEC_LOCAL", line 1345
ORA-06512: at "APEX_200100.WWV_FLOW_EXEC", line 2675
ORA-06512: at "APEX_200100.WWV_FLOW_EXEC", line 2356
ORA-06512: at "APEX_200100.WWV_FLOW_EXEC_API",~

	4	
0%
0.01431	0.00001	

- error_statement: select * from(
select a.*,row_number() over (order by null) apx$rownum from(
select *
from ((
select /*+ qb_name(apex$inner) */* from (
select x.* from "FLOWS"."FLOW_INSTANCE_DETAILS_VW" x 
where(FLOW_INSTANCE_DETAILS_VW.PRCS_ID = :PROCESS_ID
)

) d

 )) i 

)a

)where apx$rownum<=:p$_max_rows

### Steps to reproduce

Work through the Example Expenses app with Flows 21.1

After you have create an expense report, click the eye icon on page 1 

### Expected behaviour

The process flow should be displayed with no errors.

**Comment by nielsdebr** [comment]
As you mentioned, the SQL statement used wasn't correct.

I can't see a bug: the expenses app works as expected and the step-by-step tutorial has all steps written down correctly.

**Comment by Asterix7m** [comment]
OK

I coded the app following the instructions and this problem occurs.
I am not sure if I have done something wrong - the error looks to come from
the plugin itself

**Comment by nielsdebr** [comment]
Can you reproduce this behaviour on apex.oracle.com and give me access to it?

**Comment by Asterix7m** [comment]
OK I will try that and let you know. Thanks

**Comment by damthor** [comment]
Any update on this? Could not reproduce this by myself, looks like APEX generated a 'wrong' query here out of the specified region attribute (source table: FLOW_INSTANCE_DETAILS_VW with where clause: prcs_id = :PROCESS_ID).
For me the resulting query is

> select *
from ((select /*+ qb_name(apex$inner) */* from (select x.* from "FLOW_INSTANCE_DETAILS_VW" x 
where(prcs_id = :PROCESS_ID
)
) d
 )) i

which works quite fine.

**Comment by commi235** [comment]
The reason for this is because APEX wraps your original query to enable APEX specific features.
When adding a where clause in the APEX Builder one always needs to use the final column alias as APEX sees it, not a fully qualified alias which uses inner set aliases.
So instead of `set_alias.column_alias = :bind_variable` always use `column_alias = :bind_variable`.
I have verified the tutorial and it reflects this correctly.
