### ISSUE TITLE
[bug]: EXPE_P0001_VW would be better if condition tibx.sbfl_dgrm_name is null is added

### ISSUE THREAD

**Issue by ujnak** [flowsforapex/apex-flowsforapex#399]
### Flows for APEX version

21.1

### Oracle Database version

19

### Oracle APEX version

21.1

### What happened?

Definition of view EXPE_P0001_VW of Expense Claim sample application would be more appropriate if paid status is listed.

Preferable definition would be:

 where inst.dgrm_name = 'Expense Claims'
   and (tibx.sbfl_dgrm_name = 'Expense Claims' or tibx.sbfl_dgrm_name is null)

instead of:

 where inst.dgrm_name = 'Expense Claims'
   and tibx.sbfl_dgrm_name = 'Expense Claims'

### Expected behaviour

status paid are listed.

**Comment by nielsdebr** [comment]
Thanks for mentioning this. Our next release of Flows for APEX (22.1) will have a new release of the sample app included where this is addressed. It will soon be available. :)
