### ISSUE TITLE
[bug]: Definition of process Delete flow instance on Page 2 of Expense Claim needs to be changed.

### ISSUE THREAD

**Issue by ujnak** [flowsforapex/apex-flowsforapex#400]
### Flows for APEX version

21.1

### Oracle Database version

19

### Oracle APEX version

21.1

### What happened?

Current definition of "Delete flow instance" is below:

Action: Delete
Select Flow using: APEX item
APEX items(s): PROCESS_ID

Application Item PROCESS_ID is set when the process instance is created, not when delete button is pressed so the setting below would be appropriate:

Action: Delete
Select Flow using: SQL Query

SQL Query is:
select prcs_id
from flow_instances_vw
where prcs_business_ref = :P2_EXPE_ID

**Comment by nielsdebr** [comment]
Thanks for mentioning this. This issue is fixed in release 22.2 of the sample app.
