### ISSUE TITLE
[bug]: Validate JSON structure for placeholders in service task

### ISSUE THREAD

**Issue by LouisMoreaux** [flowsforapex/apex-flowsforapex#402]
### Flows for APEX version

22.1 (development)

### Oracle Database version

12.2

### Oracle APEX version

20.1

### What happened?

If the placeholder JSON object is invalid no error is raised 

### Steps to reproduce

Execute a service task with email template and an invalid JSON object.

### Expected behaviour

JSON structure is validate during execution and an error is raised when the object is not valid.
The subflow status is set to error and the error is available in the event logs.

**Comment by rallen2010** [comment]
Fixed in 22.1
