### ISSUE TITLE
[enhancement]:add  flow_globals.business_ref

### ISSUE THREAD

**Issue by madmexx2002** [flowsforapex/apex-flowsforapex#410]
### Feature description

Hi 

Expose BUSINESS_REF as a global variable in package flow_global => flow_global.business_ref
So we don't need to type the long term flow_process_vars.get_business_ref(flow_globals.process_id)

Mark

**Comment by nielsdebr** [comment]
@madmexx2002 We added your special request for 22.1. :)

**Comment by madmexx2002** [comment]
Thx. Just in time. That's how we work :)

**Comment by rallen2010** [comment]
Released in v22.1.  Closing.
