### ISSUE TITLE
Tutorial Flows for Apex: possible problem with view

### ISSUE THREAD

**Issue by abaldoni** [flowsforapex/apex-flowsforapex#421]
### Flows for APEX version

21.1

### Oracle Database version

19

### Oracle APEX version

21.2

### What happened?

The Tutorial has the user to create a view named expe_p0001_vw.
If the view is created with the following statements enabled:
```
-- enable authorization roles if you have lanes defined in your flow 
join apex_appl_acl_user_roles aclr
on upper(tibx.sbfl_current_lane) = aclr.role_static_id

```
and if in the user's Flows setup there are two or more flows with the same lane IDs and user roles, the view will have repeated lines.

### Steps to reproduce

Create two or more flows with the same lane IDs and user roles.

### Expected behaviour

The view should have distinct rows.

**Comment by LouisMoreaux** [comment]
Hi,
We have updated the view in the latest verison of the tutorial to restrict to the current application ID to avoid duplicates if you are using the same roles in others applications inside the same workspace.
