### ISSUE TITLE
Tutorial Flows for Apex: not aligned to Flows 22.1

### ISSUE THREAD

**Issue by abaldoni** [flowsforapex/apex-flowsforapex#422]
### Flows for APEX version

22.1 (development)

### Oracle Database version

19

### Oracle APEX version

21.2

### What happened?

When following the Tutorial Flows for Apex 21.1 with Flows 22.1, the following error occurs:

This Process Step has already occurred. (Incorrect step key "null" supplied while expecting step key FIiYomKWTz).

The tutorial does not specify how to setup the "step key" value in Apex.

### Steps to reproduce

Create the sample app from Tutorial Flows for Apex 21.1 with Flows version 22.1.

### Expected behaviour

The tutorial should specify which value to put in the "step key" field in Apex.

**Comment by nielsdebr** [comment]
We are working on the tutorial to be compatible with Flows for APEX 22.1. Today, it supports 21.1.

**Comment by LouisMoreaux** [comment]
Tutorial for v22.1 now available on the website.
