### ISSUE TITLE
[bug]: possible issue migrating BPMN models to v22.1 with variable expressions on userTasks 

### ISSUE THREAD

**Issue by rallen2010** [flowsforapex/apex-flowsforapex#425]
### Flows for APEX version

22.1 (latest release)

### Oracle Database version

19

### Oracle APEX version

21.1

### What happened?

We have a report of variable expression definitions being deleted from bpmn:userTask objects (only) in the XML when models are upgraded from v21.1 to v22.1.

V22.1 does rewrite and reparse BPMN models created in earlier versions to move our BPMN so that it better uses Bpmn:extension element syntax.  

Flows for APEX team is investigating.  Probably best not to migrate a system until we understand if there is a problem!

**Comment by commi235** [comment]
Reopening the issue until we have the hotfix available for "wrongly" migrated diagrams.
