### ISSUE TITLE
apex 22.1 approval task feature

### ISSUE THREAD

**Issue by j209** [flowsforapex/apex-flowsforapex#450]
Apex 22.1 has a [new feature](https://apex.oracle.com/en/platform/features/whats-new-221/) for Approvals and Unified Task List.
What effect will this new feature have on the flowforapex project?

**Comment by rallen2010** [comment]
The Flows for APEX team is working with the Oracle APEX team is to integrate workflow features between APEX and Flows for APEX, providing a range of solutions for customers and applications.  Those users who have a commitment to BPMN for business process modelling, have complex business processes, or want the use standards-based modelling will be able to use Flows for APEX.  Oracle APEX workflow features will provide declarative, rapid application development features to implement workflow processing.  Users should be able to choose, and mix and match, their workflow capabilities, as appropriate.
The Flows for APEX team is currently working on integrating an APEX Approval Component Task as a special type of a bpmn userTask, which will then use the Approval Component to get the approval decision.   We are also looking at integrating userTasks into the APEX Unified Inbox feature.  These integrations are currently targeted for the next release of Flows for APEX (v22.2).

**Comment by rallen2010** [comment]
This issue is already covered Issue #332 , which is the active development tag for this feature -- so marking as a Duplicate issue.  Closing as a duplicate.
