### ISSUE TITLE
[enhancement]: Open defined apex page on clicking a userTask in the viewer

### ISSUE THREAD

**Issue by damthor** [flowsforapex/apex-flowsforapex#462]
### Feature description

When clicking a userTask of type 'Call APEX Page' in the viewer, it would be nice to automatically open the apex page which is defined in the model.

To achieve that, the plugin needs another attribute to pass in the process id of the currently opened diagram, so the correct entry from flow_task_inbox_vw can be retrieved in the plugin using an ajax call.

If needed, you could enable/disable this future via another switchable attribute in the plugin.

### Describe alternatives you've considered

Right now, this can be achived by hooking onto the exposed 'element clicked' event in the viewer plugin. The event returns the bpmn id of the clicked object which can then be used to query the associated url from flow_task_inbox_vw.

This solution needs much more custom code and makes it more difficult to use the plugin in an end-user application declarativly.

**Comment by rallen2010** [comment]
Would this allow a user to start a future process step which is not currently the current task?  Could that rest in  users  "cherry-picking' steps of the task that they want to do & executing them in the wrong order, or without running preliminary tasks?

**Comment by damthor** [comment]
No I don't think so. The plan would be to only allow clicking on tasks that are current now (by using the data in flow_task_inbox_vw).  So you would have kind of a dashboard where you can open current process instances in the viewer and click on the tasks that have to be executed next.

**Comment by rallen2010** [comment]
Implemented in 24.1
