### ISSUE TITLE
Problem when viewing Flows Modeler

### ISSUE THREAD

**Issue by Asterix7m** [flowsforapex/apex-flowsforapex#471]
Periodically  see the this when using the Flows Modeler:

![FlowsError](https://user-images.githubusercontent.com/96238749/172799204-a3ef37f3-1545-4dc1-8135-c93a423c391b.png)

Let me know if you want to check the logs etc.

**Comment by LouisMoreaux** [comment]
Hello,
Thank you for reporting this but could you please give us more details? 
Wich Version of Flows for APEX, APEX and Oracle database are you using?
Is it possible to duplicate that in apex.oracle.com and give us access to the workspace?
Thanks
