### ISSUE TITLE
[enhancement]: Add indexes on logs tables

### ISSUE THREAD

**Issue by LouisMoreaux** [flowsforapex/apex-flowsforapex#511]
### Feature description

To improve performance while querying Flows for APEX data model, add indexes to the logs table

### Additional context

When starting to have a significant amount of instances about 400 000 then querying the table FLOW_STEP_EVENT_LOG is becoming too slow.
Adding an index on the column LGSF_PRCS_ID make the query faster but not sure if we should take a look at other tables and/or add that to the product

**Comment by rallen2010** [comment]
Indexing the Log files to speed up queries as some systems have quite large log files and the engine app does query them, we should add indexes as follows.  The tables currently have no manually created indexes or constraints (except non null constraints) and shouldn’t have FK relationships defined as the audit trails should survive when the underlying process gets deleted.
Anyhow, proposed indexes (indices)…
- Instance Event Log - If we put an index on lgpr_prcs_id, lgpr_objt_id that should speed up most of the engine app accesses which are by prcs_id, or prcs_id and objt_id inside that.
- Step Event Log - If we put an index on lgsf_prcs_id, lgsf_objt_id that should speed up most of the engine app accesses which are by prcs_id, or prcs_id and objt_id inside that.
- Variable Event Log - lgvr_prcs_id, lgvr_scope, lgvr_var_name should get most accesses
