### ISSUE TITLE
[bug]: Model can be archived despite having running instances

### ISSUE THREAD

**Issue by damthor** [flowsforapex/apex-flowsforapex#518]
### Flows for APEX version

22.2 (development)

### Oracle Database version

19

### Oracle APEX version

21.2

### What happened?

Contrary to the documentation a deprecated diagram model can be set to 'archived' while having instances running.

### Expected behaviour

You get a warning on p.7 when trying to archive a diagram, saying you still have running instances.

**Comment by rallen2010** [comment]
Fix in engine as well in 23.1 please
