### ISSUE TITLE
URL in webpage is incorrect

### ISSUE THREAD

**Issue by pguerin3** [flowsforapex/apex-flowsforapex#552]
The URL for the tutorials page is incorrect.
![image](https://user-images.githubusercontent.com/47326729/195810092-b76985ed-4da3-4cfb-bbe9-c64665d71bb8.png)

The URL is incorrectly defined as:
```
https://flowsforapex.org/latest/tutorials%20%20%F0%9F%86%95%22/
```
Instead of the correct URL of:
```
https://flowsforapex.org/latest/tutorials/
```

**Comment by LouisMoreaux** [comment]
Hello,
Thank you for reporting this issue, it is fixed now.
Regards,
Louis
