### ISSUE TITLE
[enhancement]: Mark models as startable + introduce 'process-starter-app'

### ISSUE THREAD

**Issue by damthor** [flowsforapex/apex-flowsforapex#554]
### Feature description

As an extension to the existing process-level attribute 'is-callable', diagrams should be able to be marked as 'is-startable' to imply, this diagram is a possible starting point for end user processes.

In addition to that, a 'process-starter-app', which is shipped with the release (like the engine app) could provide a dashboard style application for with a list of all startable processes and direct links to the corresponding applications.

This makes it easier to introduce new processes and make them available for end users.

### Additional context

Could be related to https://github.com/flowsforapex/apex-flowsforapex/issues/462 - maybe this will be irrelevant if most use-cases focus on the starting user task.

Also it may be an idea, to include 'process instances needing actions' to the 'starter app', showing currently active user tasks for the current user with direct links in an interactive report.

**Comment by rallen2010** [comment]
- [ ] PotentialStarters, PotentialStartingGroups and ExcludedUsers can't be based on a Process Variable -- as these expressions need to be evaluatable before a process instance is running.  Just need to remove this option from the expression types in the modeler...

**Comment by rallen2010** [comment]
Splitting this into 2 features.   this one covers:
- [x] modeler support
- [x ] parser support
- [x] engine support
- [x] flow_startable_diagrams_vw
New Issue created for a "process Hub" end-user application that could be used to start any apps that a user is authorised to start.
