### ISSUE TITLE
[bug]: missing file extension in 22.2  (Download SVG from Modeler)

### ISSUE THREAD

**Issue by Raffling19** [flowsforapex/apex-flowsforapex#562]
### Flows for APEX version

22.2 (latest)

### Oracle Database version

19c

### Oracle APEX version

22.1

### Have you used the BPMN-Linter in Flow Designer to Validate your Diagram?

Yes

### What happened?

Greetings Dear Flows for Apex Team,

when trying to download a created Model via the "Download (SVG)" button on https://apex.oracle.com/pls/apex/r/mtflows/flows4apex
it will be downloaded without a file extension, which I expect to be .svg

IMPORTANT NOTE:
work in flows for apex version 22.1

![image](https://user-images.githubusercontent.com/73223149/196955150-3625fd77-b8e2-4bd1-9a4a-6c9cecc58a2e.png)

### Steps to reproduce

1. open the Flow Modler
2. try to "Download (SVG)" --> press the button

![image](https://user-images.githubusercontent.com/73223149/196955001-b534b432-6c43-4d4e-af2a-a0c2b84a4dae.png)

### Expected behaviour

downloaded file should have a file extension (.svg)

**Comment by Raffling19** [comment]
Hi @LouisMoreaux,

mmh true it works for other models, for me aswell.
I guess its since my model still has errors.
Even though it has erros it should be able to add the file extension right?

you can check it out by going to https://apex.oracle.com/pls/apex/r/mtflows/flows4apex
and searching for the model A.1.0
as seen in the picture below.

Their it for sure does not work ^^.

![image](https://user-images.githubusercontent.com/73223149/196985075-a7d32482-c3fb-45c9-b6c4-f87bfd7d2b46.png)

Best Regards,
Nico

**Comment by LouisMoreaux** [comment]
Hello @Raffling19, 

Sorry for the late answer but it appears that your diagram is not valid (see screenshot)
![image](https://user-images.githubusercontent.com/42840524/206140197-47948861-24e0-4d06-8212-51393e50daef.png)

Did you import it? Because when I look at the XML, it looks like it contains elements that are not generated by Flows for APEX.
I recommend you to design it directly in the application.

Regards,
Louis

**Comment by rallen2010** [comment]
Closing as not a product bug.
