### ISSUE TITLE
[bug]: Complete Step still not completed

### ISSUE THREAD

**Issue by Sawalhah** [flowsforapex/apex-flowsforapex#567]
### Flows for APEX version

22.1

### Oracle Database version

19c

### Oracle APEX version

22.1

### Have you used the BPMN-Linter in Flow Designer to Validate your Diagram?

Yes

### What happened?

when completing the last step, it should go to the complete step and turn gray.
in my case, the completed step (last step) is still green and the status is running.

![image](https://user-images.githubusercontent.com/10211157/206110928-6a2bd401-a6f4-42cf-be54-63696615df3d.png)

### Steps to reproduce

Every step has one action (review request) and when the user clicks on the review button, it should go to the next step, if there is no next step, it should be completed.

**Comment by LouisMoreaux** [comment]
Hello,

Could you please provide the diagram as a bmpn export file? If you use some process variables then it is also necessary to provide an export of the current values.

Thanks

Regards,
Louis

**Comment by Sawalhah** [comment]
Hi,
This is the BPMN file (zipped).
and about the processes, I've one function call that updates my database table.
the function has one update statement.

Regards,
Mohammad

[20221208-0925_Purchase Orders - MAS_draft_1.zip](https://github.com/flowsforapex/apex-flowsforapex/files/10183073/20221208-0925_Purchase.Orders.-.MAS_draft_1.zip)

**Comment by Sawalhah** [comment]
any updates ?

**Comment by LouisMoreaux** [comment]
Hello,

Sorry for the late answer, we have tested it with the latest version of Flows for APEX (22.2) and it works fine (the flow is completed without any errors or blockers). 

Any chance for you to test it and maybe upgrade to this version? Make sure that your environment pass the prerequisites because we now only support Oracle DB 19c and higher.

Regards, 
Louis
