### ISSUE TITLE
[improvement]: Change open editor position to PL/SQL box or add new icon like APEX does

### ISSUE THREAD

**Issue by devrebeleza** [flowsforapex/apex-flowsforapex#569]
### Feature description

It would be more convenient to have an 'Open Editor' link at the top and not have to scroll down to the bottom.

Actually -> 
![Actuall Open Editor](https://user-images.githubusercontent.com/32907345/209399380-474bcd5e-ed95-450f-9c0d-a4fd12cce072.png)

### Describe alternatives you've considered

Alternatives ->
 
![New label Open Editor or Icon](https://user-images.githubusercontent.com/32907345/209399411-b74e2bad-37d2-41a4-921c-537b646100af.png)

**Comment by rallen2010** [comment]
We have slightly limited UI options with the current property panel but might have more flexibility in future as we pick up new versions of the component libraries.
