### ISSUE TITLE
[bug]: Create Model with (too) long name causes crash

### ISSUE THREAD

**Issue by mjboroski** [flowsforapex/apex-flowsforapex#570]
### Flows for APEX version

22.2 (latest)

### Oracle Database version

19c

### Oracle APEX version

22.2

### Have you used the BPMN-Linter in Flow Designer to Validate your Diagram?

Yes

### What happened?

If you create a model with invalid chars, the model will create, but the app crashes when you try to create an instance. In my particular case, it was likely a set of parentheses. This could be easily averted by validating the name field for valid characters when creating a new model.

### Steps to reproduce

Add parens to new model name then start new instance of that model.

**Comment by LouisMoreaux** [comment]
Hello,

Could you provide a bit more informations like screenshots or even a bpmn file to help us. 

I just test it and it works for me with a model containing parentheses (I also add it to the instance name)

![image](https://user-images.githubusercontent.com/42840524/210506181-12f4b91f-b545-45f2-a1c3-5f917dba38d4.png)

Regards,
Louis

**Comment by mjboroski** [comment]
Apologies, I may have been too hasty in assuming it was the parentheses. The string used was "Medical and Dental Benefits Administration (CO 4, 5 & 6) New Group Medical Enrollment Process – ACS Line of Business", so the problem could be the ampersand, long dash, comma, or even string length. When I create the model, the application does throw an error, but then creates the model anyway. Following that, the model is invalid to the application, so you cannot select "Show Details" under the Flow Management view in order to delete the remnant artifact because it brings you to the error page. Removed with a delete statement against the FLOW_DIAGRAMS table. Included images are below:
![image](https://user-images.githubusercontent.com/5354152/211865113-8f8a8e47-3761-4ed3-99a9-daf89a8ef212.png)
![image](https://user-images.githubusercontent.com/5354152/211865190-e5e5a5cf-994b-4a0b-bb9d-f3584a93631d.png)
![image](https://user-images.githubusercontent.com/5354152/211865238-1d693f73-3e0d-43f3-936c-3f9c8426f070.png)
![image](https://user-images.githubusercontent.com/5354152/211865283-91ca8f38-74ab-4f5d-aea2-307c1db2035d.png)

**Comment by rallen2010** [comment]
diagram name is defined as varchar2(150 char) - and this string is long but <130 char 

flow_engine_app_api.get_region_title puts dgrm_name || ' (Version: ' || dgrm_version || ', Status: ' || dgrm_status || ')' into a 128 byte string - which is causing an error.

Workaround for now - use shorter model name, max length around 80 char (to allow for version and status and boilerplate).

**Comment by rallen2010** [comment]
patch file for 22.2 back ported and made available in the v22.2 release assets (file fix570.sql)


closing bug now.
