### ISSUE TITLE
Delete process in docs

### ISSUE THREAD

**Issue by Sawalhah** [flowsforapex/apex-flowsforapex#574]
I was searching in [PL/SQL API](https://flowsforapex.org/latest/api/) how to delete an instance
I found this :

```
begin
 flow_api_pkg.flow_reset(
        p_process_id => 1
      , p_comment    => 'Delete Process Instance using the PL/SQL API'
   );
end;
```

but the signature was different

```
procedure flow_delete
( p_process_id  in flow_processes.prcs_id%type                            -- Process ID to delete
, p_comment     in flow_instance_event_log.lgpr_comment%type default null -- Optional comment to be added to the instance event logs   
);
```
I think it should be ```flow_delete``` in the example.

Regards,
Mohammad Sawalhah

**Comment by rallen2010** [comment]
Thanks for logging.   Yes - you are correct, the example should be 

begin
 flow_api_pkg.flow_delete(
        p_process_id => 1
      , p_comment    => 'Delete Process Instance using the PL/SQL API'
   );
end;

Online Doc for 22.2 fixed.
Source code fixed in 23.1.
