### ISSUE TITLE
[enhancement]: Update bpmn.js properties panel to next major version

### ISSUE THREAD

**Issue by damthor** [flowsforapex/apex-flowsforapex#575]
### Feature description

Version 1.0 of the bpmn.js properties panel reworks most of the UI elements by making it more modern and intuitive.
For example, tabs get replaced by collapsibles which feels much more convenient compared to APEX.

By updating the modeler plugin to that version all the custom works need to be reworked and adjusted to the new code structure internally:

- custom properties (as of Flows version 22.2)
- integration of external data (APEX meta data calls)
- integration of the Monaco Editor
- dark mode theme adjustments

**Comment by rallen2010** [comment]
### Open Issues:

- [ ] ScriptTask / serviceTask / sendTask / businessRulesTask PL/SQL code panels.   Two switches should be renamed as follows.
  - "Use APEX_EXEC' goes to 'Allow binding'
  - "Bind PAGE ITEMS (deprecated" goes to 'Bind Process Variables (Default) or Page Items (Deprecated)'
    Bind Process Variables is the FALSE option, Bind Page Items is the default, deprecated and not to be encouraged option = TRUE.
 - [ ] Variable Expressions expand not working on Safari (works in Chrome).
 - [ ] Not sure if this is a problem, but might be symptom of wider problem / non-reinitialisation of state??.  If you expand Scheduling items (Priority, Due Date) in Process, then go to UserTask > Scheduling, the items are expanded.  Close them in UserTask, return to Process - they are now closed.   So expansion state seems to be shared across objects.
