### ISSUE TITLE
[enhancement]: Enhance parser for upcoming features

### ISSUE THREAD

**Issue by commi235** [flowsforapex/apex-flowsforapex#577]
### Feature description

Catch up with the parser code to include newly added engine features (in priority order...). 

 - [x] support nested lane sets (note the unusual hierarchy of child lane objects appearing in both parent & child lanes - see issue #521  )
 - [x] parse, or failing that ignore, bpmn:group and bpmn:category (currently causes parser to fail
   This only happens if the group is inside a lane set (does not end up as an object) and there is an annotation on it.
 - [x] support task and process priorities, due dates and task assignment (all in apex extensions - not currently supported)
- [x] parse apex extensions in bpmn:sendTask, bpmn:receiveTask, intermediateCatchEvent, intermediateThrowEvent, StartEvent.
- [x] datatype ‘TIMESTAMP WITH TIME ZONE’, Modeler had to insert into the XML as ‘TIMESTAMP_WITH_TIME_ZONE’.  Can you correct that in parse_process_variables (line 650?) in Parser on the way back in, so that it’s the same as the Oracle type name in the parsed tables
 - [x] support APEX Lane attributes `apex:isRole` and `apex:role`
 - [x] support process `is_startable` attribute.  Starters / Groups / Extensions are apex:extensions so should already parse. (Check)
 - [x] support APEX:customExtension with included JSON (removing any escapes in final JSON) on all objects & connections
 - [x] missing message flow parameter `payloadVariable` on receiveTask and message Intermediate Catch Event
 - [ ] resolve the apex:taskType inconsistency. (Note that message flow flow_tasks.pkb and test suite 21 need to have some temporary fixes removed once this is finalised.

**Comment by rallen2010** [comment]
- [ ] missing the processVar extension in BasicAPEXMessage which is present on ReceiveTask and Message ICE (to specify name of proc var to store incoming payload, if any, into.).  It's a straightforward <processVar>myProcVar</processVar> value under the message...
