### ISSUE TITLE
[enhancement]: Add support for Italian

### ISSUE THREAD

**Issue by rallen2010** [flowsforapex/apex-flowsforapex#595]
### Feature description

- [x] MT 22.2 strings
- [ ] set up new language
- [x] Native proof read / correct 22.2 strings
- [ ] Load 22.2 translations
- [ ] create final deltas
- [ ] Native Proof Read / correct deltas
- [ ] Load delta translations

**Comment by lmusi** [comment]
Hi,
i would like to help you about italian translation of the projects.
Let me know if I can and how can do it at the best.
I use Oracle APEX since 2005 (rel 2.1) and in the last week i found your framework and i'm very interested on it.
See you

**Comment by LouisMoreaux** [comment]
Hi @lmusi,
Thank you for offering your help in this area. We will get back to you when we start translating the application.
Regards,
Louis
