### ISSUE TITLE
[bug]: Issue with duplicated rows in FLOW_TASK_INBOX_VW

### ISSUE THREAD

**Issue by guillermoehernandez** [flowsforapex/apex-flowsforapex#652]
### Flows for APEX version

22.2 (latest)

### Oracle Database version

19c

### Oracle APEX version

22.2

### Have you used the BPMN-Linter in Flow Designer to Validate your Diagram?

Yes

### What happened?

Hello,

I've been working on a workflow that has a timer in the last block of the process. At this point, users can decide to manually restart the business process (instance is taken some steps back in the workflow) or the timer will check for a condition every hour before moving along to the end step. If I restart once, complete the tasks, get back at the "restart" section and attempt to restart for a 2nd time, I get an error because there are duplicated records in the FLOW_TASK_INBOX_VW, even if I filter the query by SBFL_BUSINESS_REF (unique values).

Looking at the FLOW_SUBFLOWS_VW, it appears to be related to the left join with FLOWS_TIMER and the timer status.

![image](https://github.com/flowsforapex/apex-flowsforapex/assets/139909302/e9f62594-e854-4336-be73-e1e058eb565f)

### Steps to reproduce

Similar to the provided screenshot where I can manually decide to go back to a previous step or continue ahead based on a timer execution to validate a condition.

**Comment by LouisMoreaux** [comment]
Hello @guillermoehernandez,
Thank you for reporting this bug, a fix will be available soon.

**Comment by guillermoehernandez** [comment]
Thanks for the quick fix, Louis!
