### ISSUE TITLE
[bug]:  Missing Message Key var_exp_plsql_error language en

### ISSUE THREAD

**Issue by beckly007** [flowsforapex/apex-flowsforapex#654]
### Flows for APEX version

22.1

### Oracle Database version

19c

### Oracle APEX version

22.2

### Have you used the BPMN-Linter in Flow Designer to Validate your Diagram?

No

### What happened?

Flows for apex 22.1 was installed against apex 22.1, apex has now been upgraded to apex 22.2.  The existing flows are now erroring;

Missing Message Key var_exp_plsql_error language en

ORA-20987: APEX - Internal Error - Contact your application administrator.
Details about this incident are available via debug id "7960".
ORA-06512: at "APEX_220200.WWV_FLOW_CODE_EXEC_PLSQL", line 304
ORA-06512: at "APEX_220200.WWV_FLOW_DYNAMIC_EXEC", line 2654
ORA-06512: at "SYS.WWV_DBMS_SQL_APEX_220200", line 758
ORA-06512: at "APEX_220200.WWV_FLOW_ERROR", line 1074
ORA-06512: at "APEX_220200.WWV_FLOW_ERROR", line 1522
ORA-06512: at "APEX_220200.WWV_FLOW_ERROR", line 1603
ORA-06512: at "SYS.WWV_DBMS_SQL_APEX_220200", line 725
ORA-06512: at "APEX_220200.WWV_FLOW_DYNAMIC_EXEC", line 1995
ORA-06512: at "APEX_220200.WWV_FLOW_DYNAMIC_EXEC", line 2571
ORA-06512: at "APEX_220200.WWV_FLOW_CODE_EXEC_PLSQL", line 304
ORA-06512: at "APEX_220200.WWV_FLOW_CODE_EXEC", line 376
ORA-06512: at "APEX_220200.WWV_FLOW_PLUGIN_UTIL", line 3138

Missing Message Key gateway-no-route language en

ORA-01403: no data found

Am I missing some steps for flows when upgrading apex?

### Steps to reproduce

Upgrade apex from 22.1 to 22.2

### Expected behaviour

flows to run

**Comment by commi235** [comment]
Hi,

can you run the following SQL and reply here with the output?
```sql
  select fmsg_lang
       , count(*) as cnt
    from flow_messages
group by fmsg_lang
;
```

**Comment by beckly007** [comment]
Hi,

Its returning no rows

SQL>   select fmsg_lang
       , count(*) as cnt
    from flow_messages
group by fmsg_lang
;
  2    3    4    5
no rows selected

However if I check our other (not upgraded) environment which is working it returns

FMSG_LANG         CNT
---------- ----------
fr                 85
en                 85

Regards
Stuart

**Comment by commi235** [comment]
Can you detail out the steps that where taken to do the APEX upgrade?
Is this a cloned/copied environment?

You might be able to fix the issue by reinstalling all messages, but better to first check why the messages seem to have disappeared.

**Comment by beckly007** [comment]
Just followed the normal installation process for Apex.  So upgraded from 22.1 to 22.2 by running.

As sysdba

@apexins.sql apex apex temp /i/

I will have to run through the upgrade process again on another environment.

How would I reinstall the messages?  Re-run the flows install?

**Comment by commi235** [comment]
Go to the Flows for APEX 22.1 release: https://github.com/flowsforapex/apex-flowsforapex/releases/tag/v22.1
Then download "Source code (zip)", unpack.
Go to folder src/data and then run the files called
* install_engine_messages_en.sql
* install_engine_messages_fr.sql
This will reinstall all engine messages that were delivered with Flows for APEX 22.1.

**Comment by rallen2010** [comment]
Closing this now...
