### ISSUE TITLE
[bug]: 

### ISSUE THREAD

**Issue by omarsawalhah** [flowsforapex/apex-flowsforapex#673]
### Flows for APEX version

22.1

### Oracle Database version

19c

### Oracle APEX version

19.2 and lower (unsupported)

### Have you used the BPMN-Linter in Flow Designer to Validate your Diagram?

Yes

### What happened?

I tried to migrate to 22.2after installing the db objects I got
PL/SQL procedure successfully completed.

>> Install Application
--install
SP2-0310: unable to open file "application/set_environment.sql"
SP2-0310: unable to open file "application/delete_application.sql"
SP2-0310: unable to open file "application/create_application.sql"
SP2-0310: unable to open file "application/shared_components/navigation/lists/p8_subflow_row_action_menu.sql"

### Steps to reproduce

running the migrate process.
I used sqlplus
in the distribution folder
in the src folder
>migrate_all.sql

### Expected behaviour

running without errors

**Comment by commi235** [comment]
Our scripts only work with sqlcl not with SQL*Plus currently. 
You can however grab the packaged app from our release page and then install that app but don't run supporting objects.

**Comment by omarsawalhah** [comment]
OK
