### ISSUE TITLE
[bug]: Database 23c Free:  ORA 600 start flow management page 2

### ISSUE THREAD

**Issue by ljvankempen** [flowsforapex/apex-flowsforapex#674]
### Flows for APEX version

23.1 (latest)

### Oracle Database version

23c

### Oracle APEX version

23.1

### Have you used the BPMN-Linter in Flow Designer to Validate your Diagram?

No

### What happened?

In the trace of the database  I see an Ora-600 error

**Comment by commi235** [comment]
Can you enable debugging and send us more details?
An extract from the alert log would help. 
Also please send the full Oracle version you're running, including Patchset.

**Comment by ljvankempen** [comment]
SQL> select * from v$version
  2  /

BANNER                                                                           BANNER_FULL                                                                      BANNER_LEGACY                                                                        CON_ID
-------------------------------------------------------------------------------- -------------------------------------------------------------------------------- -------------------------------------------------------------------------------- ----------
Oracle Database 23c Free, Release 23.0.0.0.0 - Developer-Release                 Oracle Database 23c Free, Release 23.0.0.0.0 - Developer-Release                 Oracle Database 23c Free, Release 23.0.0.0.0 - Developer-Release                          0
                                                                                 Version 23.2.0.0.0

**Comment by ljvankempen** [comment]
Last part of altert.xml
Errors in file /opt/oracle/diag/rdbms/free/FREE/trace/FREE_ora_3695.trc  (incide
ORA-00600: internal error code, arguments: [evaopn2.h:kaf_qeeCol], [OBJT_ATTRIBU
Errors in file /opt/oracle/diag/rdbms/free/FREE/trace/FREE_ora_5292.trc  (incide
ORA-00600: internal error code, arguments: [evaopn2.h:kaf_qeeCol], [OBJT_ATTRIBU

**Comment by ljvankempen** [comment]
![image](https://github.com/flowsforapex/apex-flowsforapex/assets/76656018/70a40fae-14b4-46c5-b831-e55351503016)

**Comment by ljvankempen** [comment]
[FREE_mz00_5297_i252576_a_trm.txt](https://github.com/flowsforapex/apex-flowsforapex/files/12329764/FREE_mz00_5297_i252576_a_trm.txt)
[FREE_ora_5292_i252576._trm.txt](https://github.com/flowsforapex/apex-flowsforapex/files/12329765/FREE_ora_5292_i252576._trm.txt)
[FREE_ora_5292_i252576_trc.txt](https://github.com/flowsforapex/apex-flowsforapex/files/12329766/FREE_ora_5292_i252576_trc.txt)
[FREE_mz00_5297_i252576_a_trc.txt](https://github.com/flowsforapex/apex-flowsforapex/files/12329767/FREE_mz00_5297_i252576_a_trc.txt)

**Comment by rallen2010** [comment]
What state has this left you in?  This was a one off & everything now seems fine?   Or Flows for APEX won't work and I get this ORA-6000 overtime / often when I try to do this one thing?   or My database is corrupted or?...

**Comment by ljvankempen** [comment]
When a create a new filter with Flow Parsed = yes I got an error server crashed!!

**Comment by ljvankempen** [comment]
Maybe this has to do with the Oracle 23c Boolean field support !??

**Comment by ljvankempen** [comment]
SELECT * FROM flow_p0002_diagrams_vw f WHERE f.diagram_parsed = 'Yes'
in a sql tools gives a ora 600 error

![image](https://github.com/flowsforapex/apex-flowsforapex/assets/76656018/4dd5e869-a63b-4136-93c9-3efc3cef838d)

**Comment by ljvankempen** [comment]
I isolated the view
to
CREATE OR REPLACE VIEW TMP_LEON5 AS
SELECT
       CASE           WHEN NOT EXISTS (SELECT o.objt_id
                  FROM flow_objects2 o
                 WHERE o.objt_dgrm_id = d.dgrm_id) THEN
           'Nee'
          ELSE
           'Ja'
        END AS jaap
   FROM flow_diagrams2 d;

_flow_objects2_ and _flow_diagrams2_ are copies of _flow_objects_ and _flow_diagrams_

_SELECT * FROM tmp_leon5 WHERE jaap = 'Nee'_

Gives the same error.

I drop all columns except dgrm_id from flow_diagrams two this give the same error,
Error is gone if you delete al data in flow_diagrams2 !!!!

Looks quite sure that this is a database issue

**Comment by rallen2010** [comment]
HI.  Sorry for delay in addressing.  I installed 23c Free + APEX 23.1 + Flows for APEX 23.1 and this problem is 100% reproducible.  Also tried on a later version of Oracle 23c & the bug has been fixed already - so I think this is a Database23c Free Developers Release problem that is fixed in production releases.

Note that if you are going to use 23c Free Dev Release, you can "make it work" by removing the IR filter on diagram_parsed on Page 2.

Also note that you will currently see an error when installing Flows for APEX 23.1 on database 23c.  When installing supporting objects on 23c (which doesn't show on database 19c).   flow_log_admin.plb will fail when it is compiled.  To fix - go into APEX Data Workshop.   select the package body for FLOW_LOG_ADMIN.  Line 56 you will see 

'''sql
 ‘businessID’   value prov.prov.prov_var_vc2,
 ```

edit this to read

```sql
 ‘businessID’   value prov.prov_var_vc2,
```
and compile the package - and it should work.  (19c seems to allow this bug!)

**Comment by rallen2010** [comment]
This was a database bug in Oracle 23c Free Developer Release (23.2.0).  Oracle Database 23c Free (23.3.0) (Production) has now been released and does not include this issue.   You should now be using 23.3.0 release.  Closing...
