### ISSUE TITLE
Process stays running without running subflows [bug]: 

### ISSUE THREAD

**Issue by Hegyvari** [flowsforapex/apex-flowsforapex#702]
### Flows for APEX version

23.1 (latest)

### Oracle Database version

19c

### Oracle APEX version

newer

### Have you used the BPMN-Linter in Flow Designer to Validate your Diagram?

Yes

### What happened?

We noticed that quite a few processes stays "running" even after all their subflows terminate.

### Steps to reproduce

No idea. Launching the following query

`select * from flow_processes where prcs_status='running' and prcs_id not in (select sbfl_prcs_id from flow_subflows where sbfl_status='running') order by prcs_id desc`

I get a lot of results. If I check the subflows of one of them I get the following:

![image](https://github.com/flowsforapex/apex-flowsforapex/assets/94472043/4a0ced01-b495-47bc-91ec-0d97cf49cc45)

Would you think it would be safe for us to install a small job to close these processes based on the status of its subflows?

### Expected behaviour

The correct status in the process if there are no more subflows running.

**Comment by commi235** [comment]
To be able to analyse this, would it be possible for you to provide us with the diagram for this process?

**Comment by Hegyvari** [comment]
Sure, but I will send it to you directly if you don`t mind. If you want I can also create some audit table on flow_subflows in the database to see the changes during the lifetime of the process.

De : Moritz Klein ***@***.***>
Envoyé : mercredi 24 janvier 2024 17:10
À : flowsforapex/apex-flowsforapex ***@***.***>
Cc : Krisztian Hegyvari ***@***.***>; Author ***@***.***>
Objet : Re: [flowsforapex/apex-flowsforapex] Process stays running without running subflows [bug]: (Issue #702)


To be able to analyse this, would it be possible for you to provide us with the diagram for this process?

**Comment by Hegyvari** [comment]
Also, would it be safe to close these processes? Currently the business closes them when they stumble upon them. There is no way the engine would be able to present something to do so I guess it is.

De : Moritz Klein ***@***.***>
Envoyé : mercredi 24 janvier 2024 17:10
À : flowsforapex/apex-flowsforapex ***@***.***>
Cc : Krisztian Hegyvari ***@***.***>; Author ***@***.***>
Objet : Re: [flowsforapex/apex-flowsforapex] Process stays running without running subflows [bug]: (Issue #702)


To be able to analyse this, would it be possible for you to provide us with the diagram for this process?

**Comment by commi235** [comment]
That depends on what the analysis reveals.
You can send the diagram to klein.m80@googlemail.com.

**Comment by Hegyvari** [comment]
Hi Allen, with or without active subflows? Some of them were created after the upgrade but I have quite a few which existed at the moment of upgrade. I do not know if they had running subflows though.

I would gladly add some kind of audit tables to flow_subflows and flow_processes if you think a detailed history would help with the post mortem, this will happen again I am sure.

De : Richard Allen ***@***.***>
Envoyé : mercredi 24 janvier 2024 20:07
À : flowsforapex/apex-flowsforapex ***@***.***>
Cc : Krisztian Hegyvari ***@***.***>; Author ***@***.***>
Objet : Re: [flowsforapex/apex-flowsforapex] Process stays running without running subflows [bug]: (Issue #702)


Kristian, Are these processes that were running when they were migrated from Flows 22.2 to 23.1 by any chance?
