### ISSUE TITLE
Install doesn't support long identifiers in older database versions (pre 12c2)

### ISSUE THREAD

**Issue by lxj1996-dubug** [flowsforapex/apex-flowsforapex#705]
### Flows for APEX version

23.1 (latest)

### Oracle Database version

18c or lower (unsupported)

### Oracle APEX version

19.2 and lower (unsupported)

### Have you used the BPMN-Linter in Flow Designer to Validate your Diagram?

Yes

### What happened?

hello！When downloading version 23.1, I found that there are multiple program identifiers with more than 30 characters, for example: flow_message_flow.e_msgflow_correlated_msg_locked, compilation prompt: PLS-00114 err
![1709480192228](https://github.com/flowsforapex/apex-flowsforapex/assets/73807903/0b725ccd-0623-455d-b3a5-6ca8f58d78be)

**Comment by rallen2010** [comment]
That's one of the reasons why database 19c is the minimum supported version.  You also need APEX 20.2 or higher for the current release (Flows for APEX 23.1).  Note that by the end of 2024, of the current APEX releases, only APEX 23.2 will still be supported by Oracle, under their current support policy.
In general, we're not going to support releases of database or APEX that are no longer supported by Oracle.

**Comment by rallen2010** [comment]
Long identifiers were introduced in Oracle 12c (12.2).  In addition to this database version being out of support, the BPMN parser in Flows for APEX makes extensive use of both XML and JSON support in the database, which we found not to be stable / solid in 12c - hence moving forward to supporting 19c in 22.x

**Comment by lxj1996-dubug** [comment]
I see, my database version happens to be 12.1, which is a bit low.
