### ISSUE TITLE
[bug]: "An unexpected internal application error has occurred" while bpmn import via file- or text-upload on the website

### ISSUE THREAD

**Issue by an-koehler** [flowsforapex/apex-flowsforapex#715]
### Flows for APEX version

23.1 (latest)

### Oracle Database version

23c

### Oracle APEX version

23.1

### Have you used the BPMN-Linter in Flow Designer to Validate your Diagram?

No

### What happened?

I tried to create a model using the import function. 
The import failed with "An unexpected internal application error has occurred".

![image](https://github.com/flowsforapex/apex-flowsforapex/assets/127182350/fc9eee1f-06c7-484b-a05f-5483e5035735)

### Steps to reproduce

try to create a model with file import or text import on website https://flowsforapex.com/ords/preview/r/flows4apex/flows4apex/flow-management

The file seems to be valid because I opened it in vscode with a bpmn modeler and it worked.

I pasted the file content in block "expected behaviour"

I tried to import a flow which I created in FlowsForApex and got the same error.

### Expected behaviour

<?xml version="1.0" encoding="utf-8"?>
<definitions xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:di="http://www.omg.org/spec/DD/20100524/DI" xmlns:bpmndi="http://www.omg.org/spec/BPMN/20100524/DI" xmlns:dc="http://www.omg.org/spec/DD/20100524/DC" xmlns:ibo="http://www.ibo.de/XML/BPMN" id="ibo-0e5cc044-2f06-4fbd-8f72-1a2006d9bb7c" targetNamespace="http://www.omg.org/spec/BPMN/20100524/MODEL" exporter="ibo Software" exporterVersion="24.1.1.39" xmlns="http://www.omg.org/spec/BPMN/20100524/MODEL">
  <globalTask id="ibo-b4b9e1f4-0686-4a81-9bef-4582fbbc352f" name="Produktidee kommunizieren" />
  <globalTask id="ibo-34fbfe77-076b-4994-b72c-e99efdfcf1b2" name="Produktidee rechtlich prüfen" />
  <globalTask id="ibo-2977efab-2ea0-48fb-b5fa-b7593d7aabfa" name="weitere Informationen zum Fall zusammenstellen" />
  <globalTask id="ibo-3a29bb6b-9f00-47a1-9158-abba74dc5bae" name="Idee im System anlegen" />
  <globalTask id="ibo-96c626b2-0df6-4741-b878-9304c562554f" name="Zustimmung der Geschäftsführung einholen" />
  <globalTask id="ibo-bde2f0af-5861-4413-a779-e9cf6ddeb16e" name="Fachabteilung informieren" />
  <process id="ibo-0d3803a9-47d3-4519-8b5b-97564b7ab591" isExecutable="false">
    <laneSet id="ibo-be3729eb-3f86-4a10-9527-8c54805a1776">
      <lane id="ibo-58bae2ee-7c6d-4592-a7e6-10adadb58dbb" name="Legal">
        <flowNodeRef>ibo-24573320-708d-4c01-a9be-2280f7504534</flowNodeRef>
        <flowNodeRef>ibo-b899c575-b0c4-4204-ac6f-816c367276ac</flowNodeRef>
        <flowNodeRef>ibo-3ee9d558-ea7b-4f64-970b-c213fe09709c</flowNodeRef>
        <flowNodeRef>ibo-bc7ec3f1-5ae1-4231-bad5-f4d86e961d72</flowNodeRef>
        <flowNodeRef>ibo-a9cd9e97-a610-4ef9-b693-ca65be2a3050</flowNodeRef>
        <flowNodeRef>ibo-a58f346b-8b6d-4533-9e43-812d17f428d4</flowNodeRef>
      </lane>
      <lane id="ibo-8170cc62-c94d-41c7-8acc-d492e7716923" name="Fachabteilung  ">
        <flowNodeRef>ibo-3bff06fa-8296-49fa-950c-245cc57323b2</flowNodeRef>
        <flowNodeRef>ibo-034b63b5-bb18-4a9c-a146-53a33aff35a1</flowNodeRef>
      </lane>
      <lane id="ibo-3019998f-37ae-4ca7-a9d9-adde8c7a7579" name="Vertriebspartner/in">
        <flowNodeRef>ibo-e5a9bdc0-dbed-49de-ade8-87d3f78ccd5d</flowNodeRef>
        <flowNodeRef>ibo-ba8ff1a0-cdc1-472e-93b7-72fd63fbe16e</flowNodeRef>
        <flowNodeRef>ibo-a71ee062-7678-408c-8c54-879d006b2c90</flowNodeRef>
      </lane>
    </laneSet>
    <startEvent id="ibo-e5a9bdc0-dbed-49de-ade8-87d3f78ccd5d" name="">
      <outgoing>ibo-22194762-3980-4814-99e3-db14bf56f420</outgoing>
    </startEvent>
    <task id="ibo-ba8ff1a0-cdc1-472e-93b7-72fd63fbe16e" name="Produktidee kommunizieren">
      <incoming>ibo-22194762-3980-4814-99e3-db14bf56f420</incoming>
      <outgoing>ibo-786c48be-50cc-4493-888c-f3055a5bf2e8</outgoing>
    </task>
    <task id="ibo-24573320-708d-4c01-a9be-2280f7504534" name="Produktidee rechtlich prüfen">
      <incoming>ibo-786c48be-50cc-4493-888c-f3055a5bf2e8</incoming>
      <outgoing>ibo-e131b067-2d8c-43de-a98d-b6c409b889f5</outgoing>
    </task>
    <exclusiveGateway id="ibo-b899c575-b0c4-4204-ac6f-816c367276ac" name="" gatewayDirection="Diverging">
      <incoming>ibo-e131b067-2d8c-43de-a98d-b6c409b889f5</incoming>
      <outgoing>ibo-369ae23d-2db8-4adc-a95c-0fda78e05025</outgoing>
      <outgoing>ibo-84a2fd6c-3712-4a20-add2-0d02e85c0e23</outgoing>
      <outgoing>ibo-98f7203d-df2a-4f3a-9c6e-4b64c1a1748f</outgoing>
    </exclusiveGateway>
    <task id="ibo-3ee9d558-ea7b-4f64-970b-c213fe09709c" name="weitere Informationen zum Fall zusammenstellen">
      <incoming>ibo-369ae23d-2db8-4adc-a95c-0fda78e05025</incoming>
      <outgoing>ibo-2d2292d2-b204-400b-88d6-0e7013bdf386</outgoing>
    </task>
    <task id="ibo-3bff06fa-8296-49fa-950c-245cc57323b2" name="Idee im System anlegen">
      <incoming>ibo-00034a80-0e55-4d3c-9e03-a930699a67c4</incoming>
      <outgoing>ibo-39c169d5-19a8-45fb-8ade-a443e11b58e0</outgoing>
    </task>
    <endEvent id="ibo-a71ee062-7678-408c-8c54-879d006b2c90" name="Produktidee nict umsetzbar " ibo:iboName="Produktidee nict umsetzbar">
      <incoming>ibo-98f7203d-df2a-4f3a-9c6e-4b64c1a1748f</incoming>
      <incoming>ibo-fe54b03e-4184-4b70-8724-282c23f58430</incoming>
    </endEvent>
    <exclusiveGateway id="ibo-bc7ec3f1-5ae1-4231-bad5-f4d86e961d72" name="" gatewayDirection="Mixed">
      <incoming>ibo-84a2fd6c-3712-4a20-add2-0d02e85c0e23</incoming>
      <incoming>ibo-5349c99b-cc89-42fd-ad3c-a08e47f3931f</incoming>
      <outgoing>ibo-fe54b03e-4184-4b70-8724-282c23f58430</outgoing>
      <outgoing>ibo-e97b9ba1-f231-4fa5-8616-b3639c34c566</outgoing>
    </exclusiveGateway>
    <task id="ibo-a9cd9e97-a610-4ef9-b693-ca65be2a3050" name="Fachabteilung informieren">
      <incoming>ibo-e97b9ba1-f231-4fa5-8616-b3639c34c566</incoming>
      <outgoing>ibo-00034a80-0e55-4d3c-9e03-a930699a67c4</outgoing>
    </task>
    <task id="ibo-a58f346b-8b6d-4533-9e43-812d17f428d4" name="Zustimmung der Geschäftsführung einholen">
      <incoming>ibo-2d2292d2-b204-400b-88d6-0e7013bdf386</incoming>
      <outgoing>ibo-5349c99b-cc89-42fd-ad3c-a08e47f3931f</outgoing>
    </task>
    <endEvent id="ibo-034b63b5-bb18-4a9c-a146-53a33aff35a1" name="">
      <incoming>ibo-39c169d5-19a8-45fb-8ade-a443e11b58e0</incoming>
    </endEvent>
    <sequenceFlow id="ibo-22194762-3980-4814-99e3-db14bf56f420" name="" sourceRef="ibo-e5a9bdc0-dbed-49de-ade8-87d3f78ccd5d" targetRef="ibo-ba8ff1a0-cdc1-472e-93b7-72fd63fbe16e" />
    <sequenceFlow id="ibo-786c48be-50cc-4493-888c-f3055a5bf2e8" name="" sourceRef="ibo-ba8ff1a0-cdc1-472e-93b7-72fd63fbe16e" targetRef="ibo-24573320-708d-4c01-a9be-2280f7504534" />
    <sequenceFlow id="ibo-e131b067-2d8c-43de-a98d-b6c409b889f5" name="" sourceRef="ibo-24573320-708d-4c01-a9be-2280f7504534" targetRef="ibo-b899c575-b0c4-4204-ac6f-816c367276ac" />
    <sequenceFlow id="ibo-369ae23d-2db8-4adc-a95c-0fda78e05025" name="" sourceRef="ibo-b899c575-b0c4-4204-ac6f-816c367276ac" targetRef="ibo-3ee9d558-ea7b-4f64-970b-c213fe09709c" />
    <sequenceFlow id="ibo-84a2fd6c-3712-4a20-add2-0d02e85c0e23" name="" sourceRef="ibo-b899c575-b0c4-4204-ac6f-816c367276ac" targetRef="ibo-bc7ec3f1-5ae1-4231-bad5-f4d86e961d72" />
    <sequenceFlow id="ibo-98f7203d-df2a-4f3a-9c6e-4b64c1a1748f" name="" sourceRef="ibo-b899c575-b0c4-4204-ac6f-816c367276ac" targetRef="ibo-a71ee062-7678-408c-8c54-879d006b2c90" />
    <sequenceFlow id="ibo-2d2292d2-b204-400b-88d6-0e7013bdf386" name="" sourceRef="ibo-3ee9d558-ea7b-4f64-970b-c213fe09709c" targetRef="ibo-a58f346b-8b6d-4533-9e43-812d17f428d4" />
    <sequenceFlow id="ibo-fe54b03e-4184-4b70-8724-282c23f58430" name="Zustimmung nicht erteilt" sourceRef="ibo-bc7ec3f1-5ae1-4231-bad5-f4d86e961d72" targetRef="ibo-a71ee062-7678-408c-8c54-879d006b2c90" />
    <sequenceFlow id="ibo-e97b9ba1-f231-4fa5-8616-b3639c34c566" name="Zustimmung erteilt" sourceRef="ibo-bc7ec3f1-5ae1-4231-bad5-f4d86e961d72" targetRef="ibo-a9cd9e97-a610-4ef9-b693-ca65be2a3050" />
    <sequenceFlow id="ibo-5349c99b-cc89-42fd-ad3c-a08e47f3931f" name="" sourceRef="ibo-a58f346b-8b6d-4533-9e43-812d17f428d4" targetRef="ibo-bc7ec3f1-5ae1-4231-bad5-f4d86e961d72" />
    <sequenceFlow id="ibo-00034a80-0e55-4d3c-9e03-a930699a67c4" name="" sourceRef="ibo-a9cd9e97-a610-4ef9-b693-ca65be2a3050" targetRef="ibo-3bff06fa-8296-49fa-950c-245cc57323b2" />
    <sequenceFlow id="ibo-39c169d5-19a8-45fb-8ade-a443e11b58e0" name="" sourceRef="ibo-3bff06fa-8296-49fa-950c-245cc57323b2" targetRef="ibo-034b63b5-bb18-4a9c-a146-53a33aff35a1" />
  </process>
  <collaboration id="ibo-6c7d3dbb-9f7e-48c4-8e6e-9da90b123c7d">
    <participant id="ibo-05c40ae0-4d72-4aa5-bb58-4a69b1fdb15b" name="BPMN TEST" />
    <participant id="ibo-1a3ba2d6-547a-4e3f-b35f-052615196d69" name="Vorbereitung" processRef="ibo-0d3803a9-47d3-4519-8b5b-97564b7ab591" />
  </collaboration>
  <bpmndi:BPMNDiagram name="BPMN TEST" id="ibo-4d117f1e-4843-4c10-8bdf-fcecf388de2b">
    <bpmndi:BPMNPlane id="ibo-dd1ab68d-442a-4a68-8f2c-a0fe06d732f6" bpmnElement="ibo-6c7d3dbb-9f7e-48c4-8e6e-9da90b123c7d">
      <bpmndi:BPMNShape id="ibo-f48324a5-ee11-4eb4-b7ec-86e0bd8e9e67" bpmnElement="ibo-58bae2ee-7c6d-4592-a7e6-10adadb58dbb" isHorizontal="true">
        <dc:Bounds x="30" y="596" width="1869" height="132" />
      </bpmndi:BPMNShape>
      <bpmndi:BPMNShape id="ibo-a3d9746c-3751-4798-acef-3e002909908d" bpmnElement="ibo-8170cc62-c94d-41c7-8acc-d492e7716923" isHorizontal="true">
        <dc:Bounds x="30" y="728" width="1869" height="468" />
      </bpmndi:BPMNShape>
      <bpmndi:BPMNShape id="ibo-72368353-d174-474c-b90e-266ee9c6966b" bpmnElement="ibo-3019998f-37ae-4ca7-a9d9-adde8c7a7579" isHorizontal="true">
        <dc:Bounds x="30" y="448" width="1869" height="148" />
      </bpmndi:BPMNShape>
      <bpmndi:BPMNShape id="ibo-90385ed3-72da-4c5b-9912-d95b6ffa8d38" bpmnElement="ibo-1a3ba2d6-547a-4e3f-b35f-052615196d69" isHorizontal="true" isExpanded="true">
        <dc:Bounds x="0" y="448" width="1899" height="748" />
      </bpmndi:BPMNShape>
      <bpmndi:BPMNShape id="ibo-49317bcc-68dc-4e83-ab78-7fcabb741a02" bpmnElement="ibo-e5a9bdc0-dbed-49de-ade8-87d3f78ccd5d">
        <dc:Bounds x="84" y="496" width="48" height="48" />
      </bpmndi:BPMNShape>
      <bpmndi:BPMNShape id="ibo-1c5bf833-effc-402f-8e8f-4b7d4db357b7" bpmnElement="ibo-ba8ff1a0-cdc1-472e-93b7-72fd63fbe16e">
        <dc:Bounds x="245" y="488" width="128" height="64" />
      </bpmndi:BPMNShape>
      <bpmndi:BPMNShape id="ibo-09afaba0-a82e-4518-aaa0-581ac162450a" bpmnElement="ibo-24573320-708d-4c01-a9be-2280f7504534">
        <dc:Bounds x="540" y="612" width="128" height="64" />
      </bpmndi:BPMNShape>
      <bpmndi:BPMNShape id="ibo-5bbe6816-e8e8-4b5a-9973-08b42e2094cf" bpmnElement="ibo-b899c575-b0c4-4204-ac6f-816c367276ac">
        <dc:Bounds x="756" y="612" width="64" height="64" />
      </bpmndi:BPMNShape>
      <bpmndi:BPMNShape id="ibo-021cdde1-e17a-4735-be77-6ec356c99451" bpmnElement="ibo-3ee9d558-ea7b-4f64-970b-c213fe09709c">
        <dc:Bounds x="956" y="612" width="128" height="64" />
      </bpmndi:BPMNShape>
      <bpmndi:BPMNShape id="ibo-44d66dc1-7bc1-4743-b8e3-514e71ff6047" bpmnElement="ibo-3bff06fa-8296-49fa-950c-245cc57323b2">
        <dc:Bounds x="1540" y="764" width="128" height="64" />
      </bpmndi:BPMNShape>
      <bpmndi:BPMNShape id="ibo-da307118-d614-4e79-9919-40a70927d2f9" bpmnElement="ibo-a71ee062-7678-408c-8c54-879d006b2c90">
        <dc:Bounds x="1452" y="480" width="48" height="48" />
      </bpmndi:BPMNShape>
      <bpmndi:BPMNShape id="ibo-fc2188a0-12ad-40d3-84b0-5c63030a3994" bpmnElement="ibo-bc7ec3f1-5ae1-4231-bad5-f4d86e961d72">
        <dc:Bounds x="1277" y="612" width="64" height="64" />
      </bpmndi:BPMNShape>
      <bpmndi:BPMNShape id="ibo-2f0c2085-489e-466c-9e29-7b8e54534662" bpmnElement="ibo-a9cd9e97-a610-4ef9-b693-ca65be2a3050">
        <dc:Bounds x="1373" y="612" width="128" height="64" />
      </bpmndi:BPMNShape>
      <bpmndi:BPMNShape id="ibo-762f1964-0cdd-40f8-a660-c5f80e30938e" bpmnElement="ibo-a58f346b-8b6d-4533-9e43-812d17f428d4">
        <dc:Bounds x="1116" y="612" width="128" height="64" />
      </bpmndi:BPMNShape>
      <bpmndi:BPMNShape id="ibo-845f82fb-c96c-4ba7-a7d4-f37691681832" bpmnElement="ibo-034b63b5-bb18-4a9c-a146-53a33aff35a1">
        <dc:Bounds x="1700" y="772" width="48" height="48" />
      </bpmndi:BPMNShape>
      <bpmndi:BPMNEdge id="ibo-79d820d8-014c-4d69-8c60-552f14700aad" bpmnElement="ibo-22194762-3980-4814-99e3-db14bf56f420">
        <di:waypoint x="132" y="520" />
        <di:waypoint x="245" y="520" />
      </bpmndi:BPMNEdge>
      <bpmndi:BPMNEdge id="ibo-8c53970c-3cf1-4ed1-84c7-f571433e7484" bpmnElement="ibo-786c48be-50cc-4493-888c-f3055a5bf2e8">
        <di:waypoint x="373" y="521" />
        <di:waypoint x="383" y="521" />
        <di:waypoint x="383" y="644" />
        <di:waypoint x="540" y="644" />
      </bpmndi:BPMNEdge>
      <bpmndi:BPMNEdge id="ibo-2bf142e3-bd67-4928-87e0-500ca1439b14" bpmnElement="ibo-e131b067-2d8c-43de-a98d-b6c409b889f5">
        <di:waypoint x="668" y="644" />
        <di:waypoint x="756" y="644" />
      </bpmndi:BPMNEdge>
      <bpmndi:BPMNEdge id="ibo-876b5063-5976-46d2-be85-4bfc23c3fbbe" bpmnElement="ibo-369ae23d-2db8-4adc-a95c-0fda78e05025">
        <di:waypoint x="820" y="644" />
        <di:waypoint x="956" y="644" />
      </bpmndi:BPMNEdge>
      <bpmndi:BPMNEdge id="ibo-6f229970-a621-411d-a552-1bd4a84ee6b4" bpmnElement="ibo-84a2fd6c-3712-4a20-add2-0d02e85c0e23">
        <di:waypoint x="788" y="676" />
        <di:waypoint x="788" y="696" />
        <di:waypoint x="1309" y="696" />
        <di:waypoint x="1309" y="676" />
      </bpmndi:BPMNEdge>
      <bpmndi:BPMNEdge id="ibo-3e6afcc2-6bc5-4e90-a859-b2356729f2d1" bpmnElement="ibo-98f7203d-df2a-4f3a-9c6e-4b64c1a1748f">
        <di:waypoint x="788" y="612" />
        <di:waypoint x="788" y="504" />
        <di:waypoint x="1452" y="504" />
      </bpmndi:BPMNEdge>
      <bpmndi:BPMNEdge id="ibo-4fb14c7a-f303-44bf-a56b-1199e047bbbd" bpmnElement="ibo-2d2292d2-b204-400b-88d6-0e7013bdf386">
        <di:waypoint x="1084" y="644" />
        <di:waypoint x="1116" y="644" />
      </bpmndi:BPMNEdge>
      <bpmndi:BPMNEdge id="ibo-9e6eb7ba-586f-4a4e-876f-b8391cdbe4e1" bpmnElement="ibo-fe54b03e-4184-4b70-8724-282c23f58430">
        <di:waypoint x="1309" y="612" />
        <di:waypoint x="1309" y="601" />
        <di:waypoint x="1476" y="601" />
        <di:waypoint x="1476" y="528" />
      </bpmndi:BPMNEdge>
      <bpmndi:BPMNEdge id="ibo-0f7e69f5-b444-4d40-b189-3c79a43f2f09" bpmnElement="ibo-e97b9ba1-f231-4fa5-8616-b3639c34c566">
        <di:waypoint x="1341" y="644" />
        <di:waypoint x="1373" y="644" />
      </bpmndi:BPMNEdge>
      <bpmndi:BPMNEdge id="ibo-73c648f5-962f-43c0-90d0-4da4accf7559" bpmnElement="ibo-5349c99b-cc89-42fd-ad3c-a08e47f3931f">
        <di:waypoint x="1244" y="644" />
        <di:waypoint x="1277" y="644" />
      </bpmndi:BPMNEdge>
      <bpmndi:BPMNEdge id="ibo-ea3cd95b-6c38-4485-a92b-8928b8412100" bpmnElement="ibo-00034a80-0e55-4d3c-9e03-a930699a67c4">
        <di:waypoint x="1501" y="644" />
        <di:waypoint x="1604" y="644" />
        <di:waypoint x="1604" y="764" />
      </bpmndi:BPMNEdge>
      <bpmndi:BPMNEdge id="ibo-6289f453-9c63-420f-8029-850f62db298c" bpmnElement="ibo-39c169d5-19a8-45fb-8ade-a443e11b58e0">
        <di:waypoint x="1668" y="796" />
        <di:waypoint x="1700" y="796" />
      </bpmndi:BPMNEdge>
    </bpmndi:BPMNPlane>
  </bpmndi:BPMNDiagram>
</definitions>

**Comment by rallen2010** [comment]
I can reproduce this trying to upload one of the basic (the simplest) regression test model into this instance.  We have some reduced functionality / some features that are disabled on public facing demo instances - not sure if this is one of them without checking. ....

**Comment by rallen2010** [comment]
Closing as this doesn't reproduce on released product - expect this is "lock down" issue on the preview instance.
