### ISSUE TITLE
[bug]: Multiple scheduler jobs on shared APEX instances causes internal errors with timers

### ISSUE THREAD

**Issue by IrinaSyntegris** [flowsforapex/apex-flowsforapex#717]
### Flows for APEX version

23.1 (latest)

### Oracle Database version

19c

### Oracle APEX version

newer

### Have you used the BPMN-Linter in Flow Designer to Validate your Diagram?

Yes

### What happened?

When starting the Flows For Apex APP getting this error:
Technical Info (only available for developers)

    is_internal_error: true
    apex_error_code: APEX.CONDITION.UNHANDLED_ERROR
    original message: Error processing condition.
    original_additional_info: Contact your application administrator. Details about this incident are available via debug id "37000".
    ora_sqlcode: -1422
    ora_sqlerrm: ORA-01422: exact fetch returns more than requested number of rows

    ORA-06512: at "APEX_230200.WWV_FLOW_CODE_EXEC_PLSQL", line 234
    ORA-06512: at "APEX_230200.WWV_FLOW_DYNAMIC_EXEC", line 2647
    ORA-06512: at "CRM.FLOW_TIMERS_PKG", line 1038
    ORA-06512: at line 3
    ORA-06512: at "SYS.DBMS_SYS_SQL", line 2120
    ORA-06512: at "SYS.WWV_DBMS_SQL_APEX_230200", line 810
    ORA-06512: at "APEX_230200.WWV_FLOW_DYNAMIC_EXEC", line 2607
    ORA-06512: at "APEX_230200.WWV_FLOW_CODE_EXEC_PLSQL", line 234
    ORA-06512: at "APEX_230200.WWV_FLOW_CODE_EXEC", line 243

    component.type: APEX_APPLICATION_PAGE_REGIONS
    component.id: 10506315031163346
    component.name: Errors
    error_backtrace:

    ORA-06512: at "CRM.FLOW_TIMERS_PKG", line 1038
    ORA-06512: at line 3
    ORA-06512: at "SYS.DBMS_SYS_SQL", line 2120
    ORA-06512: at "SYS.WWV_DBMS_SQL_APEX_230200", line 810
    ORA-06512: at "APEX_230200.WWV_FLOW_DYNAMIC_EXEC", line 2607
    ORA-06512: at "APEX_230200.WWV_FLOW_CODE_EXEC_PLSQL", line 234
    ORA-06512: at "APEX_230200.WWV_FLOW_DYNAMIC_EXEC", line 2647
    ORA-06512: at "CRM.FLOW_TIMERS_PKG", line 1038
    ORA-06512: at line 3
    ORA-06512: at "SYS.DBMS_SYS_SQL", line 2120
    ORA-06512: at "SYS.WWV_DBMS_SQL_APEX_230200", line 810
    ORA-06512: at "APEX_230200.WWV_FLOW_DYNAMIC_EXEC", line 2607
    ORA-06512: at "APEX_230200.WWV_FLOW_CODE_EXEC_PLSQL", line 234
    ORA-06512: at "APEX_230200.WWV_FLOW_CODE_EXEC", line 243
    ORA-06512: at "APEX_230200.WWV_FLOW_CONDITIONS", line 189

    error_statement:

    begin wwv_flow.g_boolean := :P3_APEX_UPGRADE_DETECTED is not null or
    :P3_VERSION_MISMATCH is not null or
    flow_timers_pkg.get_timer_status = 'FALSE';
    end;

### Steps to reproduce

Starting the app Flows for Apex via Run Application from workspace. Getting the error. 
uninstalled the app after this error and installing new but still getting same error.

### Expected behaviour

The app should start without errors

**Comment by IrinaSyntegris** [comment]
This errror was coming up 4 weeks after the first installation of the app and with normal functioning. No changes made.

**Comment by rallen2010** [comment]
I think you are likely to have 2 scheduler jobs set up that are visible to the user and called APEX_FLOW_STEP_TIMERS_J.  

Run the following query 
```sql
      select enabled
       from sys.all_scheduler_jobs
       where job_name = 'APEX_FLOW_STEP_TIMERS_J';
       
```
and I think you will have > 1 row returned??
can you then repeat query using user_scheduled_jobs...

```sql
      select enabled
        from user_scheduler_jobs
       where job_name = 'APEX_FLOW_STEP_TIMERS_J';
```

Is that now only 1 row?

**Comment by IrinaSyntegris** [comment]
yes, you are right. I have got 2 jobs with the same name on the system. The user has got only one.
I have dropped one of the jobs and the app is starting again.
many thanks

**Comment by rallen2010** [comment]
We will change code in 24.1 to only search against user_scheduler_jobs instead of sys.all_scheduler_jobs and that should remove the problem.
