### ISSUE TITLE
BPMN Modeler - Properties Panel - Non Interrupting Timers - Oracle Cycle Format - Max Runs - fails if non null.

### ISSUE THREAD

**Issue by rallen2010** [flowsforapex/apex-flowsforapex#762]
### Discussed in https://github.com/flowsforapex/apex-flowsforapex/discussions/761

<div type='discussions-op-text'>

<sup>Originally posted by **bsdgithub** October 21, 2024</sup>
hello,
I'm trying to use the timer boundary event with this setup:
- cicle oracle
- timer first run 000 00:00:00
- next timeer 000 00:30:00
- max run 5
I've got the **error** on save:
 ` Get Diagram failed. TypeError: t.search is not a function
    at Wi.build (flows4apex.modeler.min.js:2:2970153)
    at flows4apex.modeler.min.js:2:2973158
    at y (flows4apex.modeler.min.js:2:2693823)
    at flows4apex.modeler.min.js:2:2973090
    at y (flows4apex.modeler.min.js:2:2693823)
    at $i.parseContainments (flows4apex.modeler.min.js:2:2972945)
    at $i.build (flows4apex.modeler.min.js:2:2970915)
    at flows4apex.modeler.min.js:2:2973421
    at y (flows4apex.modeler.min.js:2:2693823)
    at flows4apex.modeler.min.js:2:2973350`

If max run is set to null, no error.
Is it the expected behavior?
Thank you,
</div>

Customer found on 23.1, reproduces on 24.1 release candidate.
Workaround is to use ISO Cycle timer using Repeat parameter - R5/PT30M. (5 repeats at 30 minute intervals)

**Comment by damthor** [comment]
Resolved by https://github.com/flowsforapex/apex-flowsforapex/commit/68132a67e6a7d5a949e00253d0031e3901b56754

Fix will therefore be included in the final release for 24.1 on GitHub.

**Comment by rallen2010** [comment]
Fixed in 24.1.
